
create table Recette (
                         id int,
                         title varchar(256),
                         ingredientsText varchar(1024),
                         preparation varchar(1024),
                         primary key (id)
);

create table Ingredient (
                            id int,
                            name varchar(128),
                            primary key (id)
);

insert into Ingredient values (0, 'Épice');
insert into Ingredient values (1, 'Boisson gazeuse non alcoolisée');
insert into Ingredient values (2, 'Fruit à noyau');
insert into Ingredient values (3, 'Eau de vie de fruits');
insert into Ingredient values (4, 'Fruit sec');
insert into Ingredient values (5, 'Liqueur anisée');
insert into Ingredient values (6, 'Fruit');
insert into Ingredient values (7, 'Agrume');
insert into Ingredient values (8, 'Assaisonnement');
insert into Ingredient values (9, 'Légume');
insert into Ingredient values (10, 'Condiment Européen');
insert into Ingredient values (11, 'Lait');
insert into Ingredient values (12, 'Liquide');
insert into Ingredient values (13, 'Alcool');
insert into Ingredient values (14, 'Spiritueux');
insert into Ingredient values (15, 'Alcool de grain');
insert into Ingredient values (16, 'Alcool de prune');
insert into Ingredient values (17, 'Vin');
insert into Ingredient values (18, 'Noix et graine oléagineuse');
insert into Ingredient values (19, 'Amer');
insert into Ingredient values (20, 'Oeuf');
insert into Ingredient values (21, 'Fruit tropical commun');
insert into Ingredient values (22, 'Ananas');
insert into Ingredient values (23, 'Herbe commune');
insert into Ingredient values (24, 'Angostura');
insert into Ingredient values (25, 'Liqueur amère');
insert into Ingredient values (26, 'Aperol');
insert into Ingredient values (27, 'Brandy');
insert into Ingredient values (28, 'Herbe');
insert into Ingredient values (29, 'Légume tige');
insert into Ingredient values (30, 'Condiment');
insert into Ingredient values (31, 'Vin effervescent');
insert into Ingredient values (32, 'Aliments divers');
insert into Ingredient values (33, 'Légume-fruit');
insert into Ingredient values (34, 'Bouillon');
insert into Ingredient values (35, 'Liqueur');
insert into Ingredient values (36, 'Autre liqueur');
insert into Ingredient values (37, 'Sirop');
insert into Ingredient values (38, 'Autre sirop');
insert into Ingredient values (39, 'Épice commune');
insert into Ingredient values (40, 'Épice européenne');
insert into Ingredient values (41, 'Partie d\'orange');
insert into Ingredient values (42, 'Partie de citron');
insert into Ingredient values (43, 'Rhum blanc');
insert into Ingredient values (44, 'Baie');
insert into Ingredient values (45, 'Banane');
insert into Ingredient values (46, 'Vin de dessert');
insert into Ingredient values (47, 'Bouillons');
insert into Ingredient values (48, 'Herbe Asiatique');
insert into Ingredient values (49, 'Basilic');
insert into Ingredient values (50, 'Cannelle');
insert into Ingredient values (51, 'Liqueur à base de plantes');
insert into Ingredient values (52, 'Bénédictine');
insert into Ingredient values (53, 'Boisson gazeuse alcoolisée');
insert into Ingredient values (54, 'Bière');
insert into Ingredient values (55, 'Bière de fermentation haute');
insert into Ingredient values (56, 'Whisky');
insert into Ingredient values (57, 'Boisson gazeuse');
insert into Ingredient values (58, 'Vin blanc');
insert into Ingredient values (59, 'Céleri');
insert into Ingredient values (60, 'Brandy de pommes');
insert into Ingredient values (61, 'Cachaça');
insert into Ingredient values (62, 'Café');
insert into Ingredient values (63, 'Calvados');
insert into Ingredient values (64, 'Campari');
insert into Ingredient values (65, 'Cassis');
insert into Ingredient values (66, 'Sucre roux');
insert into Ingredient values (67, 'Cassonade');
insert into Ingredient values (68, 'Cava');
insert into Ingredient values (69, 'Cerise');
insert into Ingredient values (70, 'Cerise griotte');
insert into Ingredient values (71, 'Champagne');
insert into Ingredient values (72, 'Cidre de pommes');
insert into Ingredient values (73, 'Cidre brut');
insert into Ingredient values (74, 'Citron vert');
insert into Ingredient values (75, 'Citron');
insert into Ingredient values (76, 'Citronnelle');
insert into Ingredient values (77, 'Mandarine');
insert into Ingredient values (78, 'Clémentine');
insert into Ingredient values (79, 'Coca-cola');
insert into Ingredient values (80, 'Cognac');
insert into Ingredient values (81, 'Triple sec');
insert into Ingredient values (82, 'Cointreau');
insert into Ingredient values (83, 'Concombre');
insert into Ingredient values (84, 'Condiment Américain');
insert into Ingredient values (85, 'Coriandre');
insert into Ingredient values (86, 'Herbe Africaine');
insert into Ingredient values (87, 'Produit laitier');
insert into Ingredient values (88, 'Crème');
insert into Ingredient values (89, 'Crème de liqueur');
insert into Ingredient values (90, 'Crème de café');
insert into Ingredient values (91, 'Crème de cassis');
insert into Ingredient values (92, 'Sirop aux fruits');
insert into Ingredient values (93, 'Crème de noix de coco');
insert into Ingredient values (94, 'Crème fraiche');
insert into Ingredient values (95, 'Ingrédient glacé');
insert into Ingredient values (96, 'Crème glacée');
insert into Ingredient values (97, 'Crème glacée à la noix de coco');
insert into Ingredient values (98, 'Crème liquide');
insert into Ingredient values (99, 'Crémant');
insert into Ingredient values (100, 'Liqueur d\'orange');
insert into Ingredient values (101, 'Curaçao');
insert into Ingredient values (102, 'Curaçao bleu');
insert into Ingredient values (103, 'Eau');
insert into Ingredient values (104, 'Eau gazeuse');
insert into Ingredient values (105, 'Eau minérale gazeuse');
insert into Ingredient values (106, 'Menthe');
insert into Ingredient values (107, 'Gingembre');
insert into Ingredient values (108, 'Muscade');
insert into Ingredient values (109, 'Fraise');
insert into Ingredient values (110, 'Framboise');
insert into Ingredient values (111, 'Sucre');
insert into Ingredient values (112, 'Fruit à pepin');
insert into Ingredient values (113, 'Fruit tropical exotique');
insert into Ingredient values (114, 'Rhizome');
insert into Ingredient values (115, 'Get 27');
insert into Ingredient values (116, 'Gin');
insert into Ingredient values (117, 'Glaçon');
insert into Ingredient values (118, 'Glace pilée');
insert into Ingredient values (119, 'Vanille');
insert into Ingredient values (120, 'Grand marnier');
insert into Ingredient values (121, 'Grenadine');
insert into Ingredient values (122, 'Sel');
insert into Ingredient values (123, 'Stout (bière)');
insert into Ingredient values (124, 'Jus');
insert into Ingredient values (125, 'Jus de fruits');
insert into Ingredient values (126, 'Jus d\'abricots');
insert into Ingredient values (127, 'Jus d\'agrumes');
insert into Ingredient values (128, 'Jus de légumes');
insert into Ingredient values (129, 'Jus d\'ananas');
insert into Ingredient values (130, 'Jus d\'orange');
insert into Ingredient values (131, 'Jus de baies');
insert into Ingredient values (132, 'Jus de bananes');
insert into Ingredient values (133, 'Jus de canneberge');
insert into Ingredient values (134, 'Jus de cerises');
insert into Ingredient values (135, 'Jus de citron');
insert into Ingredient values (136, 'Partie de citron vert');
insert into Ingredient values (137, 'Jus de citrons verts');
insert into Ingredient values (138, 'Jus de framboises');
insert into Ingredient values (139, 'Jus de fruits de la passion');
insert into Ingredient values (140, 'Jus de fruit de la passion');
insert into Ingredient values (141, 'Jus de goyave');
insert into Ingredient values (142, 'Jus de litchis');
insert into Ingredient values (143, 'Jus de mangue');
insert into Ingredient values (144, 'Partie de paplemousse');
insert into Ingredient values (145, 'Jus de pamplemousse');
insert into Ingredient values (146, 'Jus de pêches');
insert into Ingredient values (147, 'Jus de poires');
insert into Ingredient values (148, 'Jus de pommes');
insert into Ingredient values (149, 'Jus de raisins');
insert into Ingredient values (150, 'Jus de tomates');
insert into Ingredient values (151, 'Jus multivitaminé');
insert into Ingredient values (152, 'Liqueur de café');
insert into Ingredient values (153, 'Kirsch');
insert into Ingredient values (154, 'Kiwi');
insert into Ingredient values (155, 'Kumquat');
insert into Ingredient values (156, 'Lait de coco');
insert into Ingredient values (157, 'Lait de soja');
insert into Ingredient values (158, 'Lait entier');
insert into Ingredient values (159, 'Limonade');
insert into Ingredient values (160, 'Liqueur de citron');
insert into Ingredient values (161, 'Limoncello');
insert into Ingredient values (162, 'Liqueur de fruit');
insert into Ingredient values (163, 'Liqueur d\'abricot');
insert into Ingredient values (164, 'Liqueur d\'agrume');
insert into Ingredient values (165, 'Liqueur de fraises');
insert into Ingredient values (166, 'Liqueur de litchi');
insert into Ingredient values (167, 'Liqueur de poire');
insert into Ingredient values (168, 'Liqueur de pommes');
insert into Ingredient values (169, 'Litchi');
insert into Ingredient values (170, 'Vin muté');
insert into Ingredient values (171, 'Malibu');
insert into Ingredient values (172, 'Mangalore');
insert into Ingredient values (173, 'Mangue');
insert into Ingredient values (174, 'Vermouth');
insert into Ingredient values (175, 'Martini');
insert into Ingredient values (176, 'Martini blanc');
insert into Ingredient values (177, 'Martini rosé');
insert into Ingredient values (178, 'Martini rouge');
insert into Ingredient values (179, 'Melon');
insert into Ingredient values (180, 'Melon vert');
insert into Ingredient values (181, 'Noilly Prat');
insert into Ingredient values (182, 'Noix de coco');
insert into Ingredient values (183, 'Noix de muscade');
insert into Ingredient values (184, 'Orange');
insert into Ingredient values (185, 'Orange sanguine');
insert into Ingredient values (186, 'Pamplemousse');
insert into Ingredient values (187, 'Partie d\'agrumes');
insert into Ingredient values (188, 'Pastèque');
insert into Ingredient values (189, 'Pastis');
insert into Ingredient values (190, 'Pêche');
insert into Ingredient values (191, 'Perrier');
insert into Ingredient values (192, 'Pisang Ambon');
insert into Ingredient values (193, 'Pistache');
insert into Ingredient values (194, 'Poivre');
insert into Ingredient values (195, 'Pomme');
insert into Ingredient values (196, 'Porto');
insert into Ingredient values (197, 'Prosecco');
insert into Ingredient values (198, 'Raifort');
insert into Ingredient values (199, 'Rhum');
insert into Ingredient values (200, 'Rhum ambré');
insert into Ingredient values (201, 'Saké');
insert into Ingredient values (202, 'Sauce au piment rouge');
insert into Ingredient values (203, 'Sauce tabasco');
insert into Ingredient values (204, 'Sauce worcestershire');
insert into Ingredient values (205, 'Schweppes');
insert into Ingredient values (206, 'Sel de céleri');
insert into Ingredient values (207, 'Sirop à la menthe');
insert into Ingredient values (208, 'Sirop d\'abricot');
insert into Ingredient values (209, 'Sirop d\'agrumes');
insert into Ingredient values (210, 'Sirop d\'oranges');
insert into Ingredient values (211, 'Sirop d\'orgeat');
insert into Ingredient values (212, 'Sirop de baies');
insert into Ingredient values (213, 'Sirop de cassis');
insert into Ingredient values (214, 'Sirop de citrons');
insert into Ingredient values (215, 'Sirop de fraises');
insert into Ingredient values (216, 'Sirop de fruit de la passion');
insert into Ingredient values (217, 'Sirop de gratte cul');
insert into Ingredient values (218, 'Sirop de grenadine');
insert into Ingredient values (219, 'Sirop de noix de coco');
insert into Ingredient values (220, 'Sirop de pêche');
insert into Ingredient values (221, 'Sirop de roses');
insert into Ingredient values (222, 'Sirop de sangria');
insert into Ingredient values (223, 'Sirop de sucre de canne');
insert into Ingredient values (224, 'Soda');
insert into Ingredient values (225, 'Sorbet');
insert into Ingredient values (226, 'Sorbet citron vert');
insert into Ingredient values (227, 'Sucre en poudre');
insert into Ingredient values (228, 'Sucre de canne en poudre');
insert into Ingredient values (229, 'Sucre vanillé');
insert into Ingredient values (230, 'Vin blanc sec');
insert into Ingredient values (231, 'Tequila');
insert into Ingredient values (232, 'Tranche de citron');
insert into Ingredient values (233, 'Vin rosé');
insert into Ingredient values (234, 'Vodka');
insert into Ingredient values (235, 'Yaourt');
insert into Ingredient values (236, 'Zeste de citron');
insert into Ingredient values (237, 'Zeste de citron vert');
insert into Ingredient values (238, 'Aliment');

insert into Recette values (0, 'Alerte à Malibu (Boisson de la couleurs des fameux maillots de bains... ou presque)', '50 cl de malibu coco|50 cl de gloss cerise|1 l de jus de goyave blanche|1 poignée de griottes', 'Mélanger tous les ingrédients ensemble dans un grand pichet. Placer au frais au moins 3 heures avant de déguster. Tchin tchin !!');
insert into Recette values (1, 'Aperol Spritz : Boisson italien pétillant', '1 verre d\'aperol|3 verres de vin blanc pétillant type prosecco|5 glaçons|1 orange sanguine|2 verres d\'eau pétillante', 'Préparer la quantité de Boisson souhaitée en respectant les proportions ! Garnir de glaçons et d\'un morceau d\'orange (sanguine si possible). Santé !');
insert into Recette values (2, 'Aquarium', '1/5 de curaçao|1/5 de rhum blanc|1/5 de tequila|1/5 de martini dry|1/5 de sirop de sucre de canne', 'Préparer le mélange dans un récipient transparent, ressemblant le plus possible à un aquarium, si vous n\'en avez pas! Mélanger. Ajouter des glaçons, et placer le tout au frigo. Décorer votre récipient, en y incorporant les éléments de déco. L\'effet aquarium doit être surprenant!Les proportions sont à adapter en fonction du nombre de personnes. Ce Boisson se boit normalement à la paille.');
insert into Recette values (3, 'Black velvet', '12 cl de stout|12 cl de champagne', 'Verser le champagne dans un verre et ajouter la bière');
insert into Recette values (4, 'Bloody Mary', '4 cl de vodka|12 cl de jus de tomates|0.5 cl de jus de citron|0.5 cl de sauce worcestershire|tabasco|sel de céleri|poivre', 'Mélanger les 4 premiers ingrédients directement dans un verre ou dans un verre à mélange avec des glaçons (pour refroidir sans trop diluer). Ajouter à convenance tabasco, sel de céleri et poivre.');
insert into Recette values (5, 'Bora bora', '10 cl de jus d\'ananas|6 cl de jus de fruits de la passion|2 cl de sirop de grenadine|1 cl de jus de citrons|3 glaçons', 'Réaliser cette recette au shaker. Servir dans un verre contenant des glaçons avec une rondelle d\'orange.');
insert into Recette values (6, 'Builder', '1 concombre|1 citron|1 cuillère à soupe de sucre|3 glaçons', 'Mixer le concombre dans la centrifugeuse, ajouter le jus du citron, le sucre et les glaçons. Servir dans un verre décoré d\'une tranche de citron.');
insert into Recette values (7, 'Caïpirinha', '4 cl de cachaça|1/2 citron vert|1 cuillère à soupe de sucre en poudre|glaçons', 'Couper le citron vert en deux, puis en quartier en enlevant la partie blanche centrale, responsable de l\'amertume. Mettre le citron découpé et le sucre dans un verre et piler. Ajouter la glace et la cachaça. Mélanger à la cuillère.');
insert into Recette values (8, 'Champagne en Boisson', '1 morceau de sucre roux|3 traits d\'angostura|1 cl de cognac|c 8 cl de champagne', 'Placer les ingrédients directement dans un verre de type flûte à champagne dans l\'ordre suivant : Imbiber le morceau de sucre d\'angostura, puis le mettre au fond d\'une flûte à champagne. Verser doucement le cognac (il doit recouvrir le morceau de sucre). Compléter avec du champagne bien frais.');
insert into Recette values (9, 'Citrouillette (Boisson au champagne)', 'noilly prat|champagne', 'Verser 1/3 de Nouilly Prat dans un verre puis 2/3 de Champagne bien frais. Déguster, c\'est excellent.');
insert into Recette values (10, 'Boisson Bacardi', '24 cl de rhum bacardi|6 cl de sirop de grenadine|12 cl de jus de citron', '1. Mettez le bacardi,le sirop de grenadine et le jus de citron dans un shaker.Secouez énergiquement. 2. Versez dans des verres et servez aussitôt.');
insert into Recette values (11, 'Boisson Bacardi, grenadine, citron', '24 cl de rhum bacardi|6 cl de sirop de grenadine|12 cl de jus de citron', 'Mettez le sirop de grenadine,le jus de citron et le Bacardi dans un shaker. Secouez fortement. Versez dans des verres et servez tout de suite.');
insert into Recette values (12, 'Boisson Balalaïka', '4 cl de vodka|2 cl de cointreau|4 cl de jus de citron|rondelles de citron|quelques glaçons', 'Verser les alcools et le jus de citron dans un verre haut, sur des glaçons. Décorer avec les rondelles de citron.');
insert into Recette values (13, 'Boisson Cava Vodka Lemon', '10 cl de cava|2 cl de vodka|2 cl de sirop de citron vert|1 zeste de citron vert', ' Mélanger la vodka et le sirop de citron vert. Verser le cava dans une flûte. Ajouter délicatement le mélange vodka citron vert. Décorer avec le zeste de citron vert. ');
insert into Recette values (14, 'Boisson Champagne et saké', '75 cl de champagne|16 cl de saké|4 brins de coriandre fraîche', ' Dans une flûte à Champagne, verser 4 cl de saké et compléter avec le Champagne. Ajouter un brin de coriandre par verre. A votre santé. ');
insert into Recette values (15, 'Boisson Eau de mer', '6 bouteilles de mousseux|20 cl de curaçao|70 cl de triple sec|35 cl de sirop de citrons|35 cl de sirop d\'oranges|25 cl de sucre de canne', 'Dans un grand récipient mélanger le triple sec, le curacao, le pulco citron, le pulco orange et le sucre de canne. Ensuite, ajouter les bouteilles de mousseux bien fraîches. Servir aussitôt.');
insert into Recette values (16, 'Boisson Fraisalia (sans alcool)', '500 g de fraises|50 cl de jus d\'orange|10 cl de sirop de fraise|2 l de limonade|10 glaçons', ' Placer dans un saladier les fraises coupées en morceaux, le jus d\'orange et le sirop de fraise. Laisser reposer au frais au moins 2 heures. Au moment de servir, ajouter le limonade et les glaçons. ');
insert into Recette values (17, 'Boisson Grand Paradis', '1 cl de cognac|c 5 cl de jus d\'abricot|10 cl environ de champagne', 'Mélanger au shaker le cognac et le jus d\'abricot. Verser dans un verre (type verre tulipe) et remplir de champagne.');
insert into Recette values (18, 'Boisson Lion rouge', '2 cl de whisky|2 cl de crème de cassis|2 traits de bénédictine|2 traits de pastis|glaçons', ' Remplir un shaker de glaçons, y verser les différents alcools. Fermer, puis agiter fortement quelques secondes. Servir. ');
insert into Recette values (19, 'Boisson MAP', '1/3 de martini blanc|1 trait d\'angostura|2/3 de jus de pamplemousse', 'Mettre les flûtes au congélateur. Presser le pamplemousse ou ouvrir la bouteille ou le berlingot... Verser 1/3 martini, 2/3 jus de pamplemousse et 1 trait d\'angustura. Pour la déco : poser sur chaque verre une torsade de pain aux graines de pavot et sucre dorée au four mais pétrie d\'amour et à la MAP of course...');
insert into Recette values (20, 'Boisson MTS', '50 cl de martini|25 cl de triple sec|c 25 cl de sucre de canne|50 cl de jus de fruits multivitaminés', 'Dans un grand pichet, verser tous les ingrédients et les mélanger. Laisser reposer une heure au réfrigérateur. A déguster très frais.');
insert into Recette values (21, 'Boisson Madras', '40 cl jus d\'orange|20 cl de vin blanc|sirop de grenadine', 'Mélanger le jus d\'orange avec le vin blanc. Verser le mélange dans des verres. Ajouter un filet de sirop de grenadine.');
insert into Recette values (22, 'Boisson Mexicain à ma façon', '40 cl de tequila|1 l de jus de goyave|1 l de jus d\'ananas|30 cl de jus de pomme|1 sachet de sucre vanillé|3 ou 4 feuilles de menthe', 'Mélanger les jus de goyave et d\'ananas. Ajouter la téquila et le jus de pomme. Mélanger. Ajouter le sucre vanillé et secouer jusqu\'à ce que le sucre soit fondu. Ciseler les feuilles de menthe et les incorporer au Boisson. Réserver au frigo pendant 12 à 24 heures. Attention, l\'alcool de la téquila s\'évanouit vite. On ne le sent presque plus au bout de 48 heures, ne le préparer donc pas trop tôt. Filtrer le mélange et servir bien frais.');
insert into Recette values (23, 'Boisson Pomabricotine', '45 cl de jus d\'abricots|45 cl de jus de pommes|35 cl d\'eau gazeuse|2.5 cl de liqueur|5 cl de sirop de grenadine', 'Mélanger tous les ingrédients, mettre au frais et ajouter l\'eau gazeuse fraîche au dernier moment pour conserver le pétillant.');
insert into Recette values (24, 'Boisson Pomenas', '20 cl de jus de pamplemousse|20 cl de jus d\'ananas|20 cl de jus de pommes|quelques framboises|des glaçons', 'Verser les jus dans une cruche, ajouter les framboises pour donner la couleur et des glaçons pour la fraîcheur. Servir frais.');
insert into Recette values (25, 'Boisson Whisky Cranberries', '1 dose de whisky|2 doses de jus de cranberries', 'Simplement mélanger le tout et... Santé!');
insert into Recette values (26, 'Boisson anapomise', '25 cl de jus de cerises|25 cl de jus de pommes|25 cl de jus d\'ananas|2,5 cl d\'alcool de prune|2,5 cl de sirop de sucre de canne', 'Mélangez tous les ingrédients et servir bien frais.');
insert into Recette values (27, 'Boisson apéritif', '2 l de vin blanc sec|200 g sucre|2 citrons|2 oranges|2 grands verres de rhum|1 grande bouteille de perrier', 'Mélanger tous les ingrédients et servir très frais.');
insert into Recette values (28, 'Boisson apéritif aux framboises', '1 l de vin blanc|2 l de mousseux|250 g de framboises surgelées|4 à 5 cuillères à soupe de sucre', 'Mélanger le vin blanc, les mousseux et le sucre. Ajouter les framboises surgelées... Déguster bien frais...');
insert into Recette values (29, 'Boisson au Martini', '1 l de martini blanc|1.5 l de schweppes aux agrumes|1 citron', 'Mélanger les liquides. Couper le citron en gros morceaux et l\'ajouter. Servir très frais avec des glaçons.');
insert into Recette values (30, 'Boisson au cidre', '1 bouteille de cidre brut|1/2 verre de crème de cassis|1/2 verre de cointreau', ' Mélanger le cassis et le cointreau. Tenir au frais tous les ingrédients. Et au dernier moment ajouter le cidre. ');
insert into Recette values (31, 'Boisson au kumquat et au litchi', '5 kumquats|5 litchis|1 clémentine|1/2 orange|1/2 l d\'eau|1 l de limonade', ' Mixer au mixeur tous les fruits ainsi que l\'eau jusqu\'à obtenir un mélange homogène. Ajouter le litre de limonade. Mettre au réfrigérateur 1 h. ');
insert into Recette values (32, 'Boisson au limoncello', '2 oranges|5 cl de rhum ambré|1 trait de limoncello|glaçons', 'Verser le rhum ambré dans le verre. Presser les 2 oranges, puis ajouter le jus au rhum. Ajouter ensuite le trait de Limoncello, remuer et ajouter quelques glaçons. C\'est prêt !');
insert into Recette values (33, 'Boisson aux agrumes sans alcool', '6 cl jus d\'orange|4.5 cl jus de citron jaune|2 cuillères à café de sirop de grenadine ou de fraise', ' Mesurer chacun des ingrédients et les verser dans un shaker. Bien secouer. Verser le tout dans un verre à Boisson ou une flûte à champagne. Réitérer l\'opération pour chaque personne. ');
insert into Recette values (34, 'Boisson aux framboise', '450 g de framboise surgelés|1 bouteille de sirop de sucre de canne|50 cl de kirsch|1 l de limonade|1 citron|3 bouteilles de crémant d’alsace', 'La veille : mettre les framboises, le citron en tranches, 3 verres de sirop de sucre de canne, le kirsch et la moitié de la limonade dans un gros recipient, puis laisser macérer au frigo. Mettre le reste de limonade et les bouteilles de crémant au frigo. Juste avant de servir : Rajouter à la préparation de la veille le reste de limonade et les bouteilles de Crémant. Goûter et rajouter du sucre de canne si besoin car certain crémants son plus amers que d’autre.');
insert into Recette values (35, 'Boisson bulles de melon', '2 melons|1 bouteille de crémant ou de champagne|sirop de sucre de canne|1 citron|glaçons', 'Otez les pépins des melons et mixez le melon. Pressez le citron. Mélangez le tout avec le vin pétillant, puis rajoutez des glacons et sucrez à votre goût. Servez de suite.');
insert into Recette values (36, 'Boisson café au lait', '4 à 6 cl de liqueur de café|4 à 6 cl de whisky|30 cl de lait|2 à 6 cl de sucre de canne|4 glaçons', 'Dans un shaker, verser tous les ingrédients + 2 glaçons. (répartir les autres glaçons dans le verre). Agiter le shaker jusqu\'à ce que les glaçons soient quasimment fondus. Verser dans un verre large voire évasé afin d\'obtenir une mousse onctueuse.');
insert into Recette values (37, 'Boisson cardinal', 'glace pilée|3 cl de campari|3 cl de noilly prat original dry|3 cl de gin', 'Dans un shaker, remplir de glace à moitié.Verser les ingrédients. Frapper. Servir dans un verre à Boisson et ajouter un zeste de citron.');
insert into Recette values (38, 'Boisson champagne menthe citron vert', '1 bouteille de champagne|glaçons|1 cuillère à café de jus de citron vert|2 feuilles de menthe|1 zeste de citron', ' Mettre dans un verre des glaçons à volonté. Ajouter une feuille découpée en deux et une entière pour la déco. Joindre le jus de citron vert et submerger de Champagne. Laisser reposer 2 min le temps que la saveur monte. Puis savourer ! ');
insert into Recette values (39, 'Boisson champanisé', '4 bouteilles de mousseux|1/2 bouteille cointreau|10 citrons pressés avec pulpe|2 verres de sirop de sucre de canne|des glaçons', 'Dans un grand récipient, verser le Cointreau, le jus des citrons avec leur pulpe et le sirop de sucre de canne. Verser le mousseux en dernier. Ajouter des glaçons. Servez dans des verres frais (l\'idéal est de les placer au réfrigérateur avant).');
insert into Recette values (40, 'Boisson citron-menthe (sans alcool)', '4 cl de sirop de menthe|1 trait de sirop de sucre de canne|2 cl de jus de citron vert|3 cl de jus de citron jaune|1 branche de menthe fraîche|1 tranche de citron', 'Mettre dans un shaker, avec de la glace, le sirop de menthe, le sirop de sucre et les jus de citron. Bien agiter. Verser dans un verre, décorer d\'une branche de menthe et d\'une tranche de citron.');
insert into Recette values (41, 'Boisson coco', '30 cl de vodka|1/2 l de lait|2 boules de glace à la noix de coco|2 boules de vanille|sirop de coco ou sirop de sucre de canne|5 glaçons', 'Mettre le tout dans un mixeur et dégustez.');
insert into Recette values (42, 'Boisson coco des amoureux', '1 noix de coco|rhum blanc', 'Percer la noix de coco en 3 endroits sur le dessus, et vider l\'eau à l\'intérieur. Remplir entièrement de rhum blanc. Boucher les trous en retaillant un bouchon de liège, et fermer hermétiquement en faisant couler de la cire de bougie dessus.Ranger debout, au frigo, pendant 3 semaines.');
insert into Recette values (43, 'Boisson crème de coco et banane', 'crème de coco|jus de banane|sirop de fraise|citron vert', 'Dans le fond d\'un verre verser 3 cuillères à café de crème de coco. Diluer avec du jus de banane jusqu\'a ce que le liquide ait un aspect uniforme. Ajouter un peu de sirop de cassis et quelques gouttes de jus de citron vert. Servir très frais.');
insert into Recette values (44, 'Boisson de fruits', '1 banane|1 pomme|2 kiwis|1 petit bol d\'eau|1 sachet de sucre vanillé|3 cuillères à soupe de cassonade', ' Peler et couper les fruits en morceaux. Les mettre dans le blender (ou tout autre récipient à Boisson), puis mixer le tout, en rajoutant peu à peu l\'eau, jusqu\'à obtention de la consistance voulue (moi j\'aime bien quand c\'est un peu épais). Rajouter ensuite le sucre vanillé et la cassonade, selon le goût. Mixer une dernière fois pour que le sucre s\'intègre bien au mélange. Mettre au frais pendant une petite heure et déguster ! ');
insert into Recette values (45, 'Boisson de fruits au citron vert', '10 cl de de lait de coco|20 cl de jus multivitaminé|1 cuillère à café de jus de citron vert|quelques glaçons|1 rondelle de citron vert', 'Versez 10 cl de lait de coco et 20 cl de jus multivitaminé dans un shaker. Ajoutez une cuillère à café de jus de citron vert et quelques glaçons. Mélangez bien et servez dans un verre à cockail; décorez avec une rondelle de citron vert.');
insert into Recette values (46, 'Boisson de jus de fruits pour les enfants', '5 cuillères à soupe de jus d\'ananas|3 cuillère à soupe de jus de pommes|2 glaçons|1 rondelle d\'ananas|1 rondelle de pomme|1 cuillère à café de sucre en poudre', 'Mettre le jus de pomme et le jus d\'ananas dans un grand verre, puis mélanger. Ajouter le sucre et remuer à nouveau, puis ajouter les glaçons. Mettre 5 min au frigo. Au moment de servir, mettre les rondelles d\'ananas et de pommes sur le bord du verre pour la déco.');
insert into Recette values (47, 'Boisson de pomme ambrée', '1 pomme|1 citron|6 glaçons|10 cl de jus de pomme|5 cl de calvados|10 cl de crème de cassis|champagne|un peu de cassis|morceaux de pommes|morceaux d\'ananas', 'Taillez une pomme en fines tranches et arrosez-les avec le jus d\'un citron. Réservez. Mettez 6 glaçons dans votre shaker, versez 10 cl de jus de pomme, 5 cl de calvados et 10 cl de crème de cassis. Agitez pendant 10 secondes. Répartissez dans 4 verres à Boisson, puis remplissez de champagne. Décorez de cassis, pomme et ananas.');
insert into Recette values (48, 'Boisson des dimanches de neige', 'une poignée de framboises|2 cuillères à café de sirop de gratte-cul|1/2 pamplemousse|1 orange', ' Mettre au fond d\'un joli verre, les framboises et le sirop. Ajouter le jus d\'orange et de pamplemousse pressés. Servir bien frais et regarder la neige par la fenêtre en se demandant si, vraiment, on va sortir aujourd\'hui. ');
insert into Recette values (49, 'Boisson des îles Praslin', '40 cl de jus de mangue|30 cl de jus d\'ananas|20 cl de jus de fruit de la passion|10 cl de jus de citron vert|1 cuillère à soupe de sucre', 'On mélange le tout dans une bouteille. On secoue bien pendant 20 secondes environ et on met au frigo pour que ça soit bien frais au moment de servir. A servir dans des grands verres à Boisson et avec des jolies pailles colorées.');
insert into Recette values (50, 'Boisson du verger', '4 cl de liqueur d\'abricot|5 cl de liqueur de pomme|12 cl de jus de poire|3 glaçons', 'Dans un grand verre à Boisson, installer les 3 glacons. Verser chaque ingrédient dans l\'ordre énoncé ci-dessus. Bien mélanger et déguster !!');
insert into Recette values (51, 'Boisson exotique au fruit de la passion', '1 l de limonade|35 cl de sirop de curaçao|35 cl de sirop de fruit de la passion|20 cl de jus de citron|5 glaçons', 'Dans un shaker, mélanger le sirop de curaçao, le sirop de fruit de la passion et le jus de citron. Bien secouer puis verser le mélange obtenu dans un récipient. Incorporer le litre de limonade et bien mélanger. Ajouter les 5 glaçons et servir.');
insert into Recette values (52, 'Boisson glacé tropical', '10 cl du jus de citron vert|10 cl de jus de mangue|1/2 banane|100 g de glace à la mangue|coulis de framboise', 'Mixez tous les ingrédients (sauf le coulis) jusqu\'à ce que le mélange soit bien onctueux. Décorez votre verre d\'un peu de coulis, et versez votre préparation dans ce même verre.');
insert into Recette values (53, 'Boisson italien prosecco', '75 cl de prosecco|20 litchis|30 cl de jus de litchis|10 cl de jus de baies|1 l à 1,5 l de limonade au pamplemousse pétillante, impérativement', 'Mélanger les ingrédients juste avant de servir. Verser dans des verres hauts. Éventuellement, préparer une petite brochette avec un litchi et une cerise par personne.');
insert into Recette values (54, 'Boisson la variante (à base de rosé)', '5,33l de vin rosé|0,66l de sirop d\'agrumes|4l de jus d\'orange', 'mélangez le tout Boire très frais &quot;à consommer avec modération&quot;');
insert into Recette values (55, 'Boisson light fraîcheur à la pastèque', '300 g de pastèque|1 yaourt 0%|2 cuillères de sirop de roses', 'Enlevez les pépins de la pastèque. Dans un mixeur, mettez la pastèque coupée en morceaux, le yaourt et le sirop de rose. Mixez le tout ! Servez aussitôt !!!');
insert into Recette values (56, 'Boisson léger au martini', '1 bouteille de martini rosé|1 bouteille d\'eau minérale gazeuse|2 citrons verts|une poignée de feuilles de menthe fraîche|2 cuillères à soupe de sucre', 'Verser le martini dans un grand pichet, ajouter le sucre et faire fondre.Ajouter ensuite les citrons coupés en morceaux et la menthe. Mélanger et mettre au frais au moins 4 heures (une nuit c\'est mieux). Au moment de servir, verser la bouteille d\'eau gazeuse.');
insert into Recette values (57, 'Boisson mexicanos', '12 cl de bière &quot;desperados&quot;|12 cl de jus d\'ananas|1 trait de sirop de fraises', 'Dans un verre à bière, verser un trait de sirop de fraise. Compléter avec la bière, en penchant le verre pour éviter de faire trop de mousse, et verser ensuite le jus d\'ananas. Boire très frais.');
insert into Recette values (58, 'Boisson mousseux fraise citron vert (sans alcool)', '400 g de fraises|2 c.à s.de sucre|10 cl de jus de citron vert|30 cl de limonade', 'Laver, équeuter les fraises.Les mettre dans un mixer.Ajouter le jus des citrons verts et le sucre.Mixer.Verser la limonade et mixer de nouveau.Réserver au frais jusqu\'au moment de servir. Voilà c\'est terminé !!! Bonne dégustation !!');
insert into Recette values (59, 'Boisson noix de coco-café', '2,5 cl malibu coco|2,5 cl lait de coco|2 cl de lait de soja|1 demi tasse à c. de café bien serré|1 cl de sirop de sucre de canne|5 glaçons pillés', 'Mettre les ingrédients dans un shaker. Agiter énergiquement en maintenant fermement et à deux mains le shaker et ses bouchons. Verser dans de jolis verres à Boisson.Décorer cette préparation de poudre de noisette.');
insert into Recette values (60, 'Boisson pamplemousse menthe', '1 pamplemousse|2 cuillères à soupe de glace pilée|2 cuillères à soupe de sucre roux|10 feuilles de menthe', 'Retirer le jus des pamplemousses, verser ce jus dans le blender, ajouter le reste des ingrédients et mixer le tout!!');
insert into Recette values (61, 'Boisson paradise', '10 cl de jus d\'orange|4 cl de vodka|2 cl de pisang ambon|2 cl de sucre de canne', 'Réunir les ingrédients, hormis le Pisang, dans un shaker. Frapper. Verser dans un verre à Boisson, puis ajouter le Pisang. Servir frais.');
insert into Recette values (62, 'Boisson pour les amoureux', '12 cl de jus d\'oranges|18 cl de cointreau|10 cl de cognac|3 traits de grenadine|10 cl de champagne|quelques framboises', 'Mélanger tous les ingrédients (si possible préalablement mis au frigo) à la cuillère ou au shaker. Ajouter uniquement avant de servir les framboises (pour qu\'elles gardent leur consistance) ou une heure avant si vous les souhaitées bien imbibées.');
insert into Recette values (63, 'Boisson rose au whisky', '400 g de framboises|6 brins de coriandre fraîche|5 cl de whisky|15 cl de crème fraîche|3 cuillères à soupe de pistaches non salées concassées', '1. Mixez les framboises avec la crème et 15 cl d\'eau glacée.Répartissez le mélange obtenu dans des verres. 2. Ajoutez un trait de whisky et parsemez de pistaches concassées.Décorez d\'une tige de coriandre et réservez au frais jusqu\'au moment de servir.');
insert into Recette values (64, 'Boisson rose rosé pamplemousse', '1 bouteille de vin rosé|30 cl de jus de pamplemousse rose|5 cl de grenadine', ' Dans une grande carafe, versez le sirop de grenadine puis le vin rosé et le jus de pamplemousse. Servir très frais. ');
insert into Recette values (65, 'Boisson rose sucré', '150 g de framboises|1 citron|8 glaçons|10 cl de jus de raisin|15 cl de jus d\'orange|schweppes|fruits des bois, baie', 'Versez dans le bol d\'un mixeur les framboises et le jus du citron. Mixez pour obtenir un fin coulis. Refroidissez un shaker avec 6 glaçons. Jetez l\'eau puis remettez 2 glaçons, le coulis de framboise filtré, le jus de raisin et le jus d\'orange. Ajoutez 10 secondes puis versez dans 4 verres hauts. Complétez avec le schweppes. Décorez de fruits des bois.');
insert into Recette values (66, 'Boisson rouge', 'liqueur de litchi|liqueur de fraise|jus d\'orange', 'Mélanger dans un verre les proportions suivantes: 40% de liqueur de litchi 20% de liqueur de fraise 40% de jus d\'orange. Et vive l\'apéro!');
insert into Recette values (67, 'Boisson sans alcool Cranberry-orange', '25 cl de jus de cranberry|10 cl de jus d\'orange|150 g de framboises|2 rondelles de citron ou d\'orange|1 cuillère à soupe de jus de citron', 'Mélanger les deux jus. Ajouter les framboises et le jus de citron. Mixer le tout en purée. Servir frappé ou avec quelques glaçons. Décorer vos verres d\'une rondelle de citron ou d\'orange. A votre santé !');
insert into Recette values (68, 'Boisson sans alcool KidiCana', '5 cl de jus de pomme pétillant kidibul|gingembre|1 cl de sirop de cassis|1 brin de citronnelle|1 pointe de couteau de gingembre en poudre|5 à 6 cuillères à soupe de glace pilée', 'Ciseler la citronnelle. Mettre tous les ingrédients dans un shaker. Ajouter la moitié de la glace pilée. Secouer et verser dans un verre garni du reste de la glace pilée. A votre santé !');
insert into Recette values (69, 'Boisson sans alcool Sweet Melon', '1 melon vert ovale|2 citrons verts|1 litre de jus d\'oranges|1 litre de jus d\'ananas|1/2 litre d\'eau pétillante', 'Couper la chair du melon en dès. Presser les citrons verts. Verser tous les jus de fruits dans un saladier. Ajouter les dès de melon et laisser reposer au frais pendant 2 heures. Ajouter l\'eau pétillante juste avant de servir.');
insert into Recette values (70, 'Boisson sans alcool Tropical Sunshine', '10 cl de jus d\'ananas|5 cl de jus d\'oranges|2 cl de sirop de cassis|1 cuillère à café de noix de coco râpée|glaçons', 'Verser les jus de fruits bien frais et le sirop de cassis dans un verre large. Ajouter quelques glaçons et parsemer de noix de coco râpée.');
insert into Recette values (71, 'Boisson tropical délicieux', '1/4 de l de jus d\'orange|1/4 de litre de jus de pamplemousse|1/4 de litre de jus d\'ananas|1 gros citron|20 cl de malibu|sirop de grenadine', 'Pour 1 verre : verser 5 cl de malibu, ajouter ensuite 1/3 de pamplemousse, 1/3 d\'orange et 1/3 d\'ananas ; ajouter ensuite un zeste de jus de citron et 1 trait de grenadine pour la déco.');
insert into Recette values (72, 'Boisson white russian', '30 cl de vodka|20 cl de crème de café|30 cl de lait entier|quelques glaçons', ' Mettre dans un blender 20 cl de crème de café, 30 cl de vodka et 30 cl de lait. Rajouter des glaçons et mixer quelques secondes afin que le lait mousse. Déguster ce Boisson bien frais ! ');
insert into Recette values (73, 'Coconut kiss', '3 cl de jus d\'ananas|4 cl de jus d\'oranges|2 cl de sirop de noix de coco|3 cl de crème fraîche|1 tranche d\'ananas|1 morceau d\'orange', 'Mélangez les ingrédients dans un shaker. Servir dans un verre décoré d\'un morceau d\'orange et un tranche d\'ananas');
insert into Recette values (74, 'Creole cream (Boisson)', '1 tiers de rhum blanc|1 tiers de vermouth frais mais non glacé|jus de citron|grenadine', 'Verser le rhum blanc, le vermouth, le jus de citron, puis la grenadine.');
insert into Recette values (75, 'Cuba libre', '6 cl de rhum blanc|1/2 citron vert|15 cl de coca-cola|glaçons', 'Extraire le jus du citron vert en le pressant. Ajouter les cubes de glace, puis le coca, et remuer');
insert into Recette values (76, 'Frosty lime', '1 boule de sorbet citron vert|2 cl de jus de pamplemousse|2 cl de sirop à la menthe|menthe fraîche', 'Mixer les ingrédients et servir le mélange dans un verre à coupe décoré d\'une feuille de menthe.');
insert into Recette values (77, 'Gin fizz facile', '6 cl de gin|1/2 citron vert|1 cuillère à café de sirop de sucre de canne|eau gazeuse', 'Mettez tous les ingrédients dans un shaker puis agitez énergiquement jusqu\'à ce que les parois du shaker se couvrent de buée. Versez le contenu du shaker dans les deux verres puis allongez d\'eau gazeuse. Servez frais avec de la glace pilée, une paille et une rondelle de citron vert.');
insert into Recette values (78, 'Ginger cosmo', '12 g de gingembre frais de préférence|3 cl de vodka|2 cl de triple sec|2,5 cl de jus de citrons verts|2 cl de jus de cranberry', 'Cette recette se prépare au shaker et avec un pilon. Peler le gingembre et le concasser grossièrement. Le piler dans le fond du shaker afin de faire ressortir un maximum de jus. Ajouter les autres ingrédients avec des glaçons, fermer le shaker puis shaker pendant au moins 10 secondes. Verser dans un verre à Boisson type martini en filtrant bien.');
insert into Recette values (79, 'Grand Marnier sour (Boisson)', '3 cl de grand marnier cordon rouge|3 cl de jus de citron', ' Dans un shaker mettre le Grand Marnier et le jus de citron, frappez et servir dan un grand verre à Boisson ');
insert into Recette values (80, 'Hulk ( Boisson )', '7 cl de martini blanc|5 cl de get 27|6 cl de jus de pamplemousse', 'Mélanger tous les ingrédients précités dans une petite coupe à Boisson. Ajouter un glaçon ou deux et ... déguster !!');
insert into Recette values (81, 'Le baiser de la Schtroumpfette', '2cl de vodka|2cl de curaçao|5cl de limonade|5cl de jus de banane', 'Verser tous les ingrédients dans l\'ordre dans un verre à martini ou à Boisson et servir très très frais!');
insert into Recette values (82, 'Le vandetta', '15 cl de jus d\'ananas|2 cl de sirop d\'orgeat|2 cl de sirop de fraises|5 fraises', 'Lavez et équeutez les fraises. Mixer tous les ingrédients et servez dans un verre rapidement.');
insert into Recette values (83, 'Margarita', '5 cl de tequila|3 cl de triple sec|2 cl de jus de citrons verts|sel', 'Dans un shaker, frapper les ingrédients avec des glaçons puis verser dans un verre givré au citron et au sel fin.');
insert into Recette values (84, 'Margarita à la fraise', 'glace pilée|2 à 3 citrons verts|1 barquette de fraise fraîche|20 cl de tequila|12 cl de cointreau ou triple x|2 cuillères à soupe de sucre', ' Laver et équeuter les fraises. Mettre les glacons dans un robot et mixer avec les fraises. Presser les citrons verts. Mettre la téquila, le cointreau et le jus de citron dans un doseur avec les 2 cuillères à soupe de sucre. Mélanger puis verser dans le mixer avec la glace pilée et les fraises. Décorer les verres de sucre (mouiller les verres dans du jus de citron puis les tremper dans du sucre). Répartir le Boisson dans les verres et santé ! ');
insert into Recette values (85, 'Mojito', '6 cl de rhum cubain|1/2 citron vert|8 feuilles de menthe|eau gazeuse|2 cuillères à café de sucre', 'Mettre dans un verre, les feuilles de menthe le sucre et le citron vert coupé en cubes Piler. Ajouter le rhum, de la glce pilé ou des glaçons, l\'eau gazeuse et mélanger.');
insert into Recette values (86, 'Mojito au Basilic', '5 cl de rhum blanc|eau gazeuse|5 cl de sirop de sucre de canne|1/2 cuillère de sucre roux|1/2 citron vert|feuilles de basilic|glace pilée ou glaçons', 'Couper une rondelle de Citron Vert et la déposer au fond du verre à Boisson.Mettre des glaçons dans un torchon propre, et les piler avec un marteau.Couper les feuilles de basilic en petits morceaux et les mélanger à la glace pilée.Remplir le verre de glace pilée/basilic aux 2 tiers.Ajouter les 5 cl de rhum, 5 cl de sucre de canne liquide et le jus du reste de citron vert, puis compléter avec l\'eau gazeuse.Saupoudrer de sucre roux.');
insert into Recette values (87, 'Mojito cubain', '3 cuillères à café de sucre de canne en poudre|1/2 citron vert|1 branche de menthe bien fournie|eau gazeuse|rhum|glaçons', 'Dans un verre de taille moyenne (contenance 40 cl environ), mettez 3 cuillères à café de sucre de canne. Ajoutez-y le jus d\'1/2 citron vert. Coupez en 3 ou 4 votre branche de menthe et mettez-la dans le verre (le fait de la couper permet à la saveur de la menthe de mieux se diffuser). Ajoutez un peu d\'eau gazeuse (environ 3 cl) puis avec une cuillère à café, remuez bien le tout et écrasez la menthe (insistez sur les branches plus que sur les feuilles, sinon il y aura pleins de petits bouts de menthe assez désagréables au moment de déguster votre Boisson!). Ajoutez 5 glaçons environ. Ensuite versez 6 cl de rhum (en versant à débit moyen). Pour la dose plutôt chargée, comptez jusqu\'à 5; pour la dose légère jusqu\'à 4. Enfin, complétez avec de l\'eau gazeuse.');
insert into Recette values (88, 'Negroni Boisson', '3 volumes de campari|3 volumes de martini rouge|3 volumes de gin|3 gouttes d\'angostura|1 soda|glace pilée|1 rondelle d\'orange pour décorer', 'Mélanger les ingrédients dans un verre à whisky (tumbler) et servir.');
insert into Recette values (89, 'Pink 3x6 (Boisson sans alcool)', '3 citrons verts|3 citrons jaunes|3 verres de jus de framboises|3 verres de jus de pamplemousses roses|3 cuillères à soupe de sirop de roses|3 verres de limonade|glaçons', 'Pressez les trois citrons verts et les trois citrons jaunes, mettez le jus dans un saladier. Ajoutez le jus de framboise et de pamplemousse rose. Versez trois cuillères à soupe de sirop de rose. Mélangez et gardez la préparation au frais. Juste avant de servir, versez la limonade bien fraîche et ajoutez les glaçons.');
insert into Recette values (90, 'Piña Colada', '4 cl de rhum blanc|2 cl de rhum ambré|12 cl de jus d\'ananas|4 cl de lait de coco', 'Mélanger tous les ingrédients directement dans un verre, ou dans un blender pour les mixer. C\'est prêt !');
insert into Recette values (91, 'Piña Colada (Boisson)', '125 g de crème liquide|150 g de crème de noix de coco|20 cl de jus d\'ananas non sucré|20 cl de rhum blanc|glaçons', 'Mettre tous les ingrédients, sauf les glaçons, dans un mixer et faire tourner à très grande vitesse pendant 30 sec environ. Mettre les glaçons dans les verres et verser par-dessus la crème obtenue.');
insert into Recette values (92, 'Porto Flip', '4 cl de porto|2 cl de cognac|1 oeuf|cannelle|sirop de canne|noix de muscade|glaçons', 'Dans un shaker, mettre les alcools et le sirop de canne. Ensuite ajouter les épices. Melanger avec une longue cuillère. Rajouter un oeuf et les glacons. Fermer le shaker et mixer. Servir dans un verre a Boisson, saupodrer d\'un peu de cannelle. On peut le faire uniquement avec du porto aussi.');
insert into Recette values (93, 'Punch-sangria de pastèque', '1 pastèque de 2 kg|1 orange|2 pêches|6 fraises|10 feuilles de menthe|1 l de vin blanc au choix|1/2 cuillère à café de gingembre frais ou en poudre|curaçao ou rhum', 'Laver la pastèque. Découper un &quot;couvercle&quot;, vider la pastèque avec une cuillère {si possible créer des petites boules de la grosseur de billes} Laisser 1/2 cm de chair pour ne pas crever la peau. Refroidir la pastèque vide 1 bonne heure. Réduire la moitié de la pulpe retirée en jus, y ajouter : 1 litre de vin blanc les feuilles de menthe + l orange avec sa peau et les pêches en fines tranches, laisser macérer 3 heures au réfrigérateur dans un récipient fermé. Au moment de servir ce Boisson, verser dans la pastèque avec quelques feuilles de menthe et des petites billes de pastèque.');
insert into Recette values (94, 'Raifortissimo', '5 cl de jus de pommes|3 cl de jus de citrons verts|10 g de raifort|1 kiwi|3 glaçons', 'Mixez tous les ingrédients et versez dans un verre.');
insert into Recette values (95, 'Rainbow', '10 cl de jus d\'orange|3 cl de vodka|3 cl de sirop de grenadine|2 cl de curaçao bleu', 'Recette pour 10 verres. versez la grenadine dans le shaker, remplissez le shaker de glaçons aux 2/3, versez la vodka, versez le jus d\'orange. Finissez de remplir le shaker de glaçons. Versez délicatement le curaçao, de mélangez pas, versez en filtrant dans tous les verres alignés sans vous arrêter. Servir dans des verres de type &quot;shooter&quot;. La couleur du contenu de chaque verre sera différente en créant un très bel effet visuel dégradé de type arc-en-ciel d\'un verre à l\'autre. Appelé aussi Rainbow Shot, ou Double Rainbow.');
insert into Recette values (96, 'Red Boisson', '2 cl de sirop de fraise|10 cl de jus de pêche|4 cl de vodka|2 cl de liqueur de poire|glaçons', 'Verser tous les ingrédients, hormis le sirop de fraise, dans un shaker avec 3 cubes de glace. Secouer pendant 20 secondes. Verser dans le verre, et ajouter le sirop de fraise.');
insert into Recette values (97, 'Rhum arrangé à la pomme', '25 cl de rhum|1 l de jus de pommes|10 cl de sucre de canne|cannelle', 'Dans une bouteille, mélanger les 25 cl de rhum ambré avec le litre de jus de Pomme et compléter par une rasade de Sucre de canne. Aromatisé de cannelle ou autre suivant vos goûts, puis laisser reposer au moins une journée pour que la macération soit complète.');
insert into Recette values (98, 'Rince-gouttes (Boisson)', '1,5 l de cidre|25 cl de cognac|25 cl de crème de cassis|glaçons', 'Dans un grand saladier, commencer par mettre la crème de cassis, ensuite ajoutez le cognac et finalement la bouteille de cidre. Ajoutez en dernier lieu les glaçons pour que l\'apéro reste frais.');
insert into Recette values (99, 'Sangria sans alcool', '8 cl de sirop de sangria|100 cl de jus de raisins|20 cl de jus d\'oranges|10 cl de jus de citrons|fruits de saisons', 'Mélangez le sirop et les jus dans un grand récipient. Ajoutez ensuite les fruits de saisons coupés en petits morceaux. Mettez le tout au réfrigérateur pendant 4h avant de servir.');
insert into Recette values (100, 'Screwdriver', '4 cl de vodka|12 cl de jus d\'orange', 'Dans un verre, mélanger la vodka et le jus d\'orange.');
insert into Recette values (101, 'Shoot up', '1 cl de mangalore|eau gazeuse|3 cl de sirop d\'abricot', 'Versez le mangalore et le sirop d\'abricot dans un verre et finissez par l\'eau gazeuse bien fraiche.');
insert into Recette values (102, 'Shot piquant', 'sirop de grenadine|tabasco|vodka', ' Dans un petit verre (environ 4 cm de diamètre et 5 cm de hauteur), versez 3 mm de sirop de grenadine. Ajoutez 4-6 gouttes de tabasco, puis versez très lentement 2-3 cm de vodka (froide, de préférence), pour ne pas mélanger les ingrédients. Ce Boisson se boit "cul-sec". On sent relativement peu l\'alcool au départ, car la grenadine est au fond du verre. Après quelques secondes, on ressent le piquant du tabasco. ');
insert into Recette values (103, 'Soupe au Champagne (Boisson)', '8 cl de cointreau|16 cl de sirop de sucre de canne|2 citrons verts pressés|1 bac de glaçons|75 cl de champagne', 'Verser dans un récipient le Cointreau, le sucre de canne et le jus de citron. Faire macérer pendant une nuit. Ajouter le Champagne au moment de servir avec les glaçons.');
insert into Recette values (104, 'Tequila sunrise', '6 cl de tequila|12 cl de jus d\'orange|2 cl de sirop de grenadine', 'Verser la tequila sur des glaçons dans le verre. Compléter avec le jus d\'orange et remuer. Verser doucement le sirop de grenadine dans le verre pour qu\'il tombe au fond.');
insert into Recette values (105, 'Ti\'punch', '6 cl de rhum blanc|2 cl de sirop de sucre de canne|citron vert|glace pilée', 'Couper les extrémités du citron vert et couper le en demi-rondelles. Mettre 4 demi-rondelles dans un verre et écraser avec un pilon ou une cuillère. Ajouter le rhum et le sirop de sucre de canne. Ajouter de la glace pilée et mélanger.');
insert into Recette values (106, 'Tutti Boisson', '2 cl de sirop de fraise|2 cl de sirop de pêche|4 cl de vodka|4 cl de liqueur de pomme|5 glaçons', 'Mélanger au shaker puis ajouter les glaçons. Pour un petit effet, mettre le sirop de fraise après le mélange.');
insert into Recette values (107, 'Virevoltage', '1 cl de malibu|1 cl de liqueur de litchi|jus d\'ananas|jus de pomme|sirop de fraise', 'Dans un verre à Boisson rempli de glaçons, mettre le Malibu et le Soho. Remplir la moitié du verre de jus d\'ananas et l\'autre moitié de jus de pomme, ajouter une goutte de sirop de fraise ou grenadine. Servir très frais. Bon cokctail à tous!');
